### ISSUE TITLE
intended use - multiple projects?

### ISSUE THREAD

**Issue by Lkruitwagen** [ESA-PhiLab/iris#15]
Hello! Very nice project!

I was wondering if I could ask - is there an intended pattern if I want to host multiple projects on the same server? I see that a `project` has a given `$HOST` - is that if I want to serve multiple projects on the same server? Thanks!

**Comment by aliFrancis** [comment]
The `host` option is by default 127.0.0.1 (your local machine), meaning that you can only access it from there. If you would like people to be able to login and work on your project from an external machine, then it can be set to another IP address which you can expose (by configuring your router and computer's IP settings).

For multiple projects, I suggest you set `port` to different values in their respective config files. We haven't explicitly tested the behaviour when hosting multiple projects, though, so if there are issues then please get back to us.

**Comment by Lkruitwagen** [comment]
Awesome! Yes, I'm thinking of a setup where on a remote machine I can build multiple projects reverse proxied with `gunicorn` and `nginx` and then my labellers can just access them using via their browsers and the IP address + port
