### ISSUE TITLE
Could not predict the mask due to a server problem

### ISSUE THREAD

**Issue by totony4real** [ESA-PhiLab/iris#20]
Hi there,
After I do the prediction by pressing AI button and fill the mask, there is an error message says: Could not predict the mask due to a server problem!
<img width="795" alt="image" src="https://user-images.githubusercontent.com/111908902/186232782-7a13618a-2fde-4677-a650-cd06568dcad1.png">

Could you please advise a little bit about that?

Thanks,
Tony

**Comment by aliFrancis** [comment]
Thanks for using IRIS!

Could I ask for a bit more information about the error? Please copy/paste the error string that is printed in the terminal on which you are running the IRIS server. This error message that you have shown from the client is very generic, and doesn't tell us much about what is happening.
