### ISSUE TITLE
FR: control to adjust marker size

### ISSUE THREAD

**Issue by robmarkcole** [ESA-PhiLab/iris#40]
I'm using a magic mouse which doesn't have a scroller, which I think is used to adjust the marker size. This FR is to request a dedicated control for this

<img width="644" alt="image" src="https://github.com/ESA-PhiLab/iris/assets/11855322/87bde52a-0d11-4e59-bdbe-871eea9be79e">

**Comment by robmarkcole** [comment]
OK screenshotting using shift, which evidently toggled the control

**Comment by aliFrancis** [comment]
Yeah, I have added a note to the Usage section in README, to recommend using keyboard + mouse with scrollwheel.
