### ISSUE TITLE
Bug in Bing view?

### ISSUE THREAD

**Issue by robmarkcole** [ESA-PhiLab/iris#41]
When I zoom in the bing view does not update
<img width="994" alt="image" src="https://github.com/ESA-PhiLab/iris/assets/11855322/6e2f5430-b192-4734-889c-f02b6848590d">

**Comment by aliFrancis** [comment]
This is (unfortunately) not a bug. The bing view is a separate plugin that is mainly used for extra high-resolution context. The spatial extent of the bing view also does not closely match the other views at initialization, and no mask is displayed on top.

**Comment by robmarkcole** [comment]
A 'solution' would be to pre-create the HR tile as another chip

**Comment by robmarkcole** [comment]
@aliFrancis example with NAIP image, both images cropped and resampled to the same:

<img width="1913" alt="image" src="https://github.com/ESA-PhiLab/iris/assets/11855322/077b4e0a-c0d8-4de5-96da-7fa4c9fb6e05">
