### ISSUE TITLE
FR: mark null option

### ISSUE THREAD

**Issue by robmarkcole** [ESA-PhiLab/iris#45]
This image has no change, a button to mark `null` would be great

<img width="629" alt="image" src="https://github.com/ESA-PhiLab/iris/assets/11855322/0e92ff30-fcf0-44dd-a22d-fbc89dbfd26d">

**Comment by aliFrancis** [comment]
This pop-up should only happen if you try to train the AI without having drawn pixels for two classes. If the mask is all one class, then you just need to blow the paintbrush cursor size up and paint the whole thing. You then don't need to train the AI at all and can just save the mask.

I will leave open in case I misunderstood the FR and you would like something else to be implemented

**Comment by robmarkcole** [comment]
`you just need to blow the paintbrush cursor size up and paint the whole thing` -> makes sense, thanks!
