### ISSUE TITLE
No such file or directory: 'xx_final.npy'

### ISSUE THREAD

**Issue by robmarkcole** [ESA-PhiLab/iris#53]
On starting a labelling session with a new config:
```
No such file or directory: '/mnt/scratch/home/robin.cole/iris/xx_v2/xx_v3.iris/segmentation/3/1_final.npy'
```
I recall having this before in https://github.com/ESA-PhiLab/iris/issues/46

I was previously labelling a dataset with the same structure, perhaps some metadata is persisted - checked and deleted all db file I could find

**Comment by robmarkcole** [comment]
OK this error is cleared after I fix a mistake in the config: 
```
    "view_groups": {
        "default": ["RGB"] # value WAS wrong
    }    
```

**Comment by aliFrancis** [comment]
Great, closing. This relates to something more generally along with a few previous issues, which is that some kind of config checking procedure that spots errors would be very helpful for debugging when things like this occur
