### ISSUE TITLE
IRIS loading indefinitely

### ISSUE THREAD

**Issue by thomasvaujour** [ESA-PhiLab/iris#54]
Hello!
I have been using IRIS and everything has been fine, until now.
I think the only modification I have done in the configuration file (since the last time it worked properly) is changing the path to save the masks in the "segmentation" section. I don't think it is the root of the problem because I have already done it before without any issue.

However, now, when I launch IRIS, it says "Loading masks..." forever and I can't click on anything (see the picture below).

![image](https://github.com/ESA-PhiLab/iris/assets/152421521/3f9ff1c5-2c67-4bfe-9a7a-f5ae4f5ff3b5)

Nothing looks different than usual in the terminal by the way, just a succession of these two lines: 
127.0.0.1 - - [29/Nov/2023 17:28:33] "GET /user/get/current HTTP/1.1" 200 -
127.0.0.1 - - [29/Nov/2023 17:28:33] "GET /image_info/2011-05 HTTP/1.1" 200 -

Do you have an idea of what could be the problem and what I could do?

Thanks a lot for your help!

**Comment by thomasvaujour** [comment]
Update on this issue:

I think I had too many masks and files in the same IRIS project and everything was mixed up. I have sorted my masks and files, created several IRIS projects to split them and now it seems to work again properly.

**Comment by aliFrancis** [comment]
Hi Thomas, glad things are working again! If you are changing the paths in the config or other things about the masks, you will often need to clear the project's .iris directory, as there can be clashes between what's in the database files and the files that actually exist. 

Cool data, by the way!

**Comment by thomasvaujour** [comment]
Thanks for the explanation! It was indeed the case. I've changed the paths several times so there must have been many conflicts.
